# 注册中心的配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#本服务的配置
server:
  port: 8762
spring:

  #服务名称
  application:
    name: service-hi

  #mysql配置
  datasource:
    url: jdbc:mysql://47.93.47.111:3306/answer?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: answer
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #redis缓存配置
  redis:
    host: 10.12.1.134
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
#日志
logging:
  level:
    com.wu.springcloud: DEBUG
    java.sql: INFO
  path: D:/wu/project/logs/safe
  file: D:/wu/project/logs/safe/safe.log

#mybatis
mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
 # type-aliases-package:  com.cci.market
  config-location: classpath:mybatis-config.xml
